In [1]:
import pandas as pd
import os
import matplotlib as plt
import numpy as np

In [2]:
data=pd.read_csv(r"Medical_Examiner_Case_Archive%2C_2014_to_present.csv")
data.head()

,X,Y,CASENUMBER,INCIDENT_DATE,DEATH_DATE,AGE,GENDER,RACE,LATINO,MANNER,...,RESIDENCE_ZIP,CommDistrict,AGE_GROUP,OPIOID_RELATED,GUN_RELATED,chi_ward,chi_commarea,last_edited_date,OBJECTID,Shape
0,1179718.653,1903140.088,ME2014-00627,2014/09/21 15:00:00+00,2014/09/21 18:50:00+00,25.0,Male,Black,NO,UNDETERMINED,...,60608,3.0,20-29,No,No,42.0,NEAR NORTH SIDE,2021/02/18 23:13:11+00,1,NaN
1,1178751.595,1763864.964,ME2014-00649,2014/09/22 21:40:00+00,2014/09/22 21:55:00+00,61.0,Male,Black,NO,NATURAL,...,60411,5.0,60-69,No,No,NaN,NaN,2021/02/12 04:14:46+00,2,NaN
2,1116158.893,1860456.187,ME2014-00712,2014/09/27 21:58:00+00,2014/09/27 22:10:00+00,51.0,Male,White,NO,NATURAL,...,60525,16.0,50-59,No,No,NaN,NaN,2021/08/14 01:48:01+00,3,NaN
3,1172548.740,1853286.833,ME2014-00792,2014/10/02 05:00:00+00,2014/10/02 19:15:00+00,55.0,Male,Black,NO,NATURAL,...,NaN,3.0,50-59,No,No,17.0,AUBURN GRESHAM,2021/02/18 23:13:11+00,4,NaN
4,1175954.392,1828477.039,ME2014-00869,2014/10/08 15:30:00+00,2014/10/08 15:35:00+00,67.0,Male,Black,NO,NATURAL,...,60628,5.0,60-69,No,No,34.0,WEST PULLMAN,2021/02/18 23:13:11+00,5,NaN

In [3]:
# converting data on the incident date into a list
y=(data["INCIDENT_DATE"])
Year=[]
for i in y:
    i=str(i)
    i=i[0:4]
    i=float(i)
    Year.append(i)

In [4]:
# converting data on the manner of death into a list
y=(data["MANNER"])
Manner=[]
for i in y:
    Manner.append(i)

In [5]:
# converting data on the incident zip into a list
y=(data["INCIDENT_ZIP"])
Zip=[]
for i in y:
    Zip.append(i)

In [6]:
# creating a list of the positions of all the deaths in each list that took place in 2020
twentytwenty=[]
for i in range(0,56979):
    if Year[i]==2020:
        twentytwenty.append(i)

In [7]:
# creating a list of the zip code where each 2020 homicide in cook county took place
Zips=[]
for i in twentytwenty:
    if (Manner[i])=="HOMICIDE":
        Zips.append(Zip[i])

In [8]:
nZips=np.array(Zips)
L=np.unique(nZips)

In [9]:
# printing how many homicides occured in each zip code of cook county in 2020
for p in L:
    print(p)
    print(Zips.count(p))

46312
2
46323
1
46394
1
46404
1
46406
1
60004
1
60007
1
60008
1
60010
1
60016
1
60025
1
60090
1
60104
1
60131
1
60133
2
60153
15
60160
1
60162
1
60164
1
60165
2
60169
2
60171
1
60176
1
60201
2
60202
2
60302
2
60402
2
60406
5
60409
5
60411
12
60416
1
60419
6
60426
19
60428
8
60429
3
60430
1
60432
1
60433
1
60438
1
60443
2
60451
2
60452
2
60455
1
60458
1
60459
1
60461
1
60466
2
60469
1
60471
1
60472
2
60476
1
60478
2
60482
1
60484
1
60501
1
60505
1
60525
1
60538
1
60546
1
60602
1
60604
2
60605
2
60607
3
60608
20
60609
26
60610
4
60611
1
60612
29
60613
1
60614
1
60615
5
60616
8
60617
44
60618
7
60619
44
60620
43
60621
35
60622
10
60623
45
60624
60
60625
6
60626
6
60628
46
60629
25
60630
6
60632
18
60634
3
60636
42
60637
26
60638
4
60639
11
60640
4
60641
4
60642
3
60643
14
60644
61
60645
4
60646
1
60647
7
60649
26
60651
41
60652
6
60653
10
60654
3
60655
2
60656
1
60659
4
60660
2
60707
3
60804
7
60827
13
60901
1
nan
0